tagFormat: "v0.${version}" # PVP prefixed

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - successCommentCondition: false
      failureCommentCondition: false
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./bin/release verify"
      prepareCmd: "./bin/release prepare '0.${nextRelease.version}'"
      publishCmd: "./bin/release publish '0.${nextRelease.version}'"

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//g, "rc-")}'
