tagFormat: "v0.${version}" # PVP prefixed

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - successCommentCondition: false
      failCommentCondition: false
  - - "semantic-release-hackage"
    - packageName: "shellwords"
      versionPrefix: "0."
      cabalCmd: stack
      sdistOptions: >-
        --pvp-bounds lower
        --tar-dir dist-newstyle/sdist

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//g, "rc-")}'
