name: Release

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: tag
        uses: freckle/haskell-tag-action@v1

      - if: steps.tag.outputs.tag
        run: stack upload --pvp-bounds lower .
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_API_KEY }}
          STACK_YAML: stack-lts12.yaml
