name: Release

on:
  push:
    branches:
      - main
      - rc/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            git+https://github.com/pbrisbin/semantic-release-hackage.git#pb/next
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          HACKAGE_TOKEN: ${{ secrets.HACKAGE_API_KEY }}
          STACK_YAML: stack-lts12.yaml
